/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Pyboard {
  constructor(path: string, baudRate: number)
  cat(path: string): string
  ls(path: string): Array<string>
  exists(path: string): boolean
}
